server:
  port: 1001
spring:
  application:
    name: chat-eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/ #http://mione:1000/eureka/ #,http://mitwo:2000/eureka/
