server:
  port: 1003
spring:
  application:
    name: chat-eureka-consumer
eureka:
  client:
    serviceUrl:
        defaultZone: http://localhost:1000/eureka/ #http://mione:1000/eureka/ #,http://mitwo:2000/eureka/
