server:
  port: 3000

# 配置服务注册中心
eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:1000/eureka/ # http://mione:1000/eureka/ #,http://mitwo:2000/eureka/

# Git仓库配置
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tlyong1992/ChatCloud/
          search-paths: chat-config/chat-cloud-config-repo
          username: username
          password: password
  application:
    name: chat-cloud-config-server

## HttpBasic 认证
#security:
#  user:
#    name: miyaow # 默认user
#    password: miyaow
